"""Image processing strategy package."""

from .operations import (
    BgrChannelOperation,
    BlurOperation,
    CartoonOperation,
    CenterCropOperation,
    GrayHistogramOperation,
    EdgeDetectionOperation,
    GrayscaleOperation,
    HsvChannelOperation,
    HsvSpaceOperation,
    MorphologyOperation,
    OperationRegistry,
    PerspectiveWarpOperation,
    RgbHistogramOperation,
    RgbSpaceOperation,
    RotateOperation,
    ScaleOperation,
    ThresholdOperation,
    build_default_registry,
)

__all__ = [
    "BgrChannelOperation",
    "BlurOperation",
    "CartoonOperation",
    "CenterCropOperation",
    "GrayHistogramOperation",
    "EdgeDetectionOperation",
    "GrayscaleOperation",
    "HsvChannelOperation",
    "HsvSpaceOperation",
    "MorphologyOperation",
    "OperationRegistry",
    "PerspectiveWarpOperation",
    "RgbHistogramOperation",
    "RgbSpaceOperation",
    "RotateOperation",
    "ScaleOperation",
    "ThresholdOperation",
    "build_default_registry",
]
