"""Public API package for image classification."""

from .facade import (
    ClassificationModelInfo,
    ImageClassificationConfig,
    ImageClassificationService,
    PredictionItem,
    PredictionResult,
    PretrainedWeightInfo,
    create_image_classification_service,
    download_pretrained_weight,
    get_default_service,
    import_pretrained_weight,
    list_classification_models,
    load_classifier,
    load_pretrained_classifier,
    predict_image,
    predict_with_pretrained,
    pretrained_weight_status,
    split_classification_dataset,
    supported_models,
    train_classifier,
    validate_classification_dataset,
)

__all__ = [
    "ClassificationModelInfo",
    "ImageClassificationConfig",
    "ImageClassificationService",
    "PredictionItem",
    "PredictionResult",
    "PretrainedWeightInfo",
    "create_image_classification_service",
    "download_pretrained_weight",
    "get_default_service",
    "import_pretrained_weight",
    "list_classification_models",
    "load_classifier",
    "load_pretrained_classifier",
    "predict_image",
    "predict_with_pretrained",
    "pretrained_weight_status",
    "split_classification_dataset",
    "supported_models",
    "train_classifier",
    "validate_classification_dataset",
]
